// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC_EvxEC5NG6kfFBD3aZtKaskV0xRlkPxI',
    appId: '1:654234056126:web:ee876d0dffb729e437b5ef',
    messagingSenderId: '654234056126',
    projectId: 'walletflex-4d9d2',
    authDomain: 'walletflex-4d9d2.firebaseapp.com',
    storageBucket: 'walletflex-4d9d2.appspot.com',
    measurementId: 'G-86ZPEF42R3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDCMCWSJgb-NFHS411goBT0P2cNxSDnDXc',
    appId: '1:654234056126:android:b9a08f1aeabe59e537b5ef',
    messagingSenderId: '654234056126',
    projectId: 'walletflex-4d9d2',
    storageBucket: 'walletflex-4d9d2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDrw37ZwPGukQHQpswhTTLekIUqxgMQilw',
    appId: '1:654234056126:ios:fd40e56e27dadd1737b5ef',
    messagingSenderId: '654234056126',
    projectId: 'walletflex-4d9d2',
    storageBucket: 'walletflex-4d9d2.appspot.com',
    iosBundleId: 'com.example.walletFlex',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDrw37ZwPGukQHQpswhTTLekIUqxgMQilw',
    appId: '1:654234056126:ios:fd40e56e27dadd1737b5ef',
    messagingSenderId: '654234056126',
    projectId: 'walletflex-4d9d2',
    storageBucket: 'walletflex-4d9d2.appspot.com',
    iosBundleId: 'com.example.walletFlex',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC_EvxEC5NG6kfFBD3aZtKaskV0xRlkPxI',
    appId: '1:654234056126:web:d82ee2a336851b3f37b5ef',
    messagingSenderId: '654234056126',
    projectId: 'walletflex-4d9d2',
    authDomain: 'walletflex-4d9d2.firebaseapp.com',
    storageBucket: 'walletflex-4d9d2.appspot.com',
    measurementId: 'G-Y71TWL2HP4',
  );
}
